Repository FRONTENDBOOTCAMP-13th/Final-15-HOLATAJA, pull requests merged in 2025-08, with the labels that each got.

#171 🔀 feat: 결제 페이지 기능 구현
  src/app/checkout/CheckOutForm.tsx
  src/app/checkout/page.tsx
  src/types/user.ts
Labels: 💡Feature

#175 🔀 feat: 제품 상세 페이지-타건 사운드 체험 기능 구현 완료
  public/sounds/keyboardSound_sample.m4a
  src/app/products/[id]/page.tsx
  src/app/products/components/KeySoundDemo.tsx
  src/components/SoundToggle.tsx
Labels: 💡Feature

#176 🔀refactor: 로그인폼 모달창 적용 완료
  src/app/auth/login/LoginForm.tsx
Labels: ♻️Refactor

#178 🔀 conf: DBinit 파일 수정 및 이미지 경로 수정 반영
  api/dbinit/openmarket/data.json
  api/dbinit/team/data.json
  next.config.ts
  src/app/carts/components/CartProductCard.tsx
  src/app/checkout/page.tsx
  src/app/my/[id]/page.tsx
  src/app/my/components/BookmarkTab.tsx
  src/app/my/components/OrderTab.tsx
  src/app/products/[id]/page.tsx
  src/app/products/components/ProductList.tsx
  src/app/products/page.tsx
  src/data/actions/product.ts
Labels: 🎉Init, ➕Add

#184 🔀 delete: data.js파일 삭제
  api/dbinit/openmarket/data.js
  api/dbinit/team/data.js
Labels: 🗑️Remove

#185 🔀 test: 2차 배포 테스트
  api/dbinit/openmarket/data.js
  api/dbinit/team/data.js
Labels: 🗑️Remove, 🧪Test

#195 🔀 refactor: 상품 상세 페이지 Q&A/마이페이지 Q&A 답변 조회 방식 변경
  src/app/my/components/QnATab.tsx
  src/app/products/[id]/page.tsx
  src/components/QnA.tsx
Labels: 🐛BugFix, ♻️Refactor

#199 🔀 feat: 파비콘 적용 및 헤더 아이콘 정렬
  public/icon/favicon_dark.svg
  public/icon/favicon_light.svg
  src/app/favicon.ico
  src/app/layout.tsx
  src/components/Header.tsx
Labels: 💡Feature, 🎨Style

#201 🔀 fix: 구매 내역 목록/상세 페이지 수정사항 반영
  api/dbinit/team/data.json
  src/app/my/[id]/page.tsx
  src/app/my/components/HistoryCard.tsx
  src/app/my/components/OrderTab.tsx
  src/types/order.ts
Labels: 🐛BugFix, 💡Feature, 📝Documentation

#200 🔀 feat: 메타데이터 적용
  src/app/layout.tsx
Labels: 💡Feature

#209 🔀 refactor: 로그인 시도 후 로직 변경
  src/app/auth/login/LoginForm.tsx
  src/app/layout.tsx
Labels: ♻️Refactor

#210 🔀 refactor: 회원가입 폼 모달 구현
  src/app/auth/signup/SignupForm.tsx
  src/app/carts/components/CartProductCard.tsx
Labels: ♻️Refactor

#213 🔀 design: 장바구니 카드 UI 수정(자릿수 변경에 따른 틀어짐 방지, 아이콘 위치 수정 및 공백 조정)
  src/app/carts/components/CartContainer.tsx
  src/app/carts/components/CartProductCard.tsx
Labels: 🎨Style

#218 🔀 fix: DBinit용 data.json 수정
  api/dbinit/team/data.json
Labels: 🎉Init

#226 🔀 fix: 3차 배포테스트-build 에러 수정
  src/app/components-preview/page.tsx
  src/app/my/components/QnATab.tsx
Labels: 🐛BugFix, 🧪Test

#227 🔀 feat: 3차 배포테스트
  api/dbinit/team/data.json
  public/icon/favicon_dark.svg
  public/icon/favicon_light.svg
  public/sounds/air60-v2-low-blue-switch.mp3
  public/sounds/air60-v2-low-brown-switch.mp3
  public/sounds/air60-v2-low-red-switch.mp3
  public/sounds/air75-v2-low-blue-switch.mp3
  public/sounds/air75-v2-low-brown-switch.mp3
  public/sounds/air75-v2-low-red-switch.mp3
  public/sounds/air96-v2-low-blue-switch.mp3
  public/sounds/air96-v2-low-brown-switch.mp3
  public/sounds/air96-v2-low-red-switch.mp3
  public/sounds/bh65-high-jade-switch.mp3
  public/sounds/bh65-high-jdae_pro.mp3
  public/sounds/field75-he-high-magnetic_white-switch.mp3
  public/sounds/field75-high-magnetic_jade-switch.mp3
  public/sounds/halo75-v2-lemon-switch.mp3
  public/sounds/halo75-v2-mint-switch.mp3
  public/sounds/halo75-v2-raspberty-switch.mp3
  public/sounds/halo75-v2-red_silent-switch.mp3
  public/sounds/kick75-low-nano-silent-switch.mp3
  public/sounds/kick75-low-nano-silver-switch.mp3
  public/sounds/kick75-low-nano_brown-switch.mp3
  public/sounds/kick75-low-nano_red-switch.mp3
  src/app/auth/login/LoginForm.tsx
  src/app/auth/login/page.tsx
  src/app/auth/signup/SignupForm.tsx
  src/app/auth/signup/page.tsx
  src/app/carts/components/CartContainer.tsx
  src/app/carts/components/CartProductCard.tsx
  src/app/carts/page.tsx
  src/app/checkout/CheckOutForm.tsx
  src/app/checkout/page.tsx
  src/app/favicon.ico
  src/app/layout.tsx
  src/app/my/[id]/page.tsx
  src/app/my/components/HistoryCard.tsx
  src/app/my/components/OrderTab.tsx
  src/app/my/components/QnATab.tsx
  src/app/my/page.tsx
  src/app/products/[id]/page.tsx
  src/components/Carousel.tsx
  src/components/Header.tsx
  src/components/QnA.tsx
  src/data/functions/carts.ts
  src/types/order.ts
Labels: 🧪Test

#228 🔀 Refactor: 상품 상세 기본 옵션값 설정
  src/app/checkout/CheckOutForm.tsx
  src/app/products/[id]/ProductPostForm.tsx
Labels: ♻️Refactor

#230 🔀 style: 전체적인 스타일 통일, 수정
  public/npay-logo.png
  public/npay-logo.svg
  public/toss-logo.png
  src/app/auth/login/LoginForm.tsx
  src/app/auth/login/page.tsx
  src/app/auth/signup/SignupForm.tsx
  src/app/auth/signup/page.tsx
  src/app/carts/components/CartContainer.tsx
  src/app/carts/components/CartProductCard.tsx
  src/app/carts/components/CartSummary.tsx
  src/app/checkout/CheckOutForm.tsx
  src/app/checkout/page.tsx
  src/app/globals.css
  src/app/my/[id]/page.tsx
  src/app/my/components/BookmarkTab.tsx
  src/app/my/components/HistoryCard.tsx
  src/app/my/components/OrderTab.tsx
  src/app/my/components/QnATab.tsx
  src/app/my/components/ReviewTab.tsx
  src/app/my/components/UserInfo.tsx
  src/app/my/page.tsx
  src/app/products/[id]/Review.tsx
  src/app/products/[id]/page.tsx
  src/app/products/components/ProductList.tsx
  src/app/products/components/SearchBar.tsx
  src/app/products/components/SortToggle.tsx
  src/app/products/page.tsx
  src/components/Button.tsx
  src/components/CheckboxButton.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/Input.tsx
  src/components/Modal.tsx
  src/components/OrderdCard.tsx
  src/components/ProductImg.tsx
  src/components/QnA.tsx
  src/components/QuantityCount.tsx
  src/components/Select.tsx
  src/components/Tab.tsx
  src/components/Textarea.tsx
Labels: 🎨Style, 🔐Accessibility

#232 🔀 fix: Input 컴포넌트 readonly 속성 삭제
  src/components/Input.tsx
Labels: 🐛BugFix

#236 🔀 style: footer 모바일에서 줄바꿈되게 수정, 장바구니 카드 텍스트 크기 변경, 접근성 개선
  src/app/carts/components/CartProductCard.tsx
  src/app/products/components/SortToggle.tsx
  src/components/Footer.tsx
Labels: 🎨Style, 🔐Accessibility

#237 🔀 feat: 타건 사운드 체험 기능 타건음 파일 맵핑 완료
  api/dbinit/team/data.json
  public/sounds/halo75-v2-raspberry-switch.mp3
  src/app/products/[id]/page.tsx
  src/app/products/components/KeySoundDemo.tsx
  src/types/product.ts
Labels: 💡Feature

#238 🔀 feat: 상품 상세 페이지 로그인 필요 모달 구현
  src/app/products/[id]/PostForm.tsx
  src/app/products/[id]/ProductPostForm.tsx
  src/app/products/[id]/page.tsx
  src/app/products/components/SearchBar.tsx
  src/components/Modal.tsx
  src/components/QnA.tsx
  src/components/QuantityCount.tsx
Labels: 💡Feature, 🔐Accessibility

#240 🔀 feat: 최종 배포테스트 - 기능 추가 및 오류 수정
  api/dbinit/team/data.json
  public/sounds/halo75-v2-raspberry-switch.mp3
  src/app/carts/components/CartProductCard.tsx
  src/app/products/[id]/PostForm.tsx
  src/app/products/[id]/ProductPostForm.tsx
  src/app/products/[id]/page.tsx
  src/app/products/components/KeySoundDemo.tsx
  src/app/products/components/SearchBar.tsx
  src/app/products/components/SortToggle.tsx
  src/components/Footer.tsx
  src/components/Modal.tsx
  src/components/QnA.tsx
  src/components/QuantityCount.tsx
  src/types/product.ts
Labels: 🐛BugFix, 💡Feature, 🎨Style, 🧪Test

#244 🔀 fix: 로그인 성공 모달 표시 내용 변경(title 추가/description 줄바꿈 추가)
  src/app/auth/login/LoginForm.tsx
Labels: 🎨Style

#245 🔀 hotfix: 프리텐다드 폰트 적용
  public/font/pretendardvariable.css
  public/font/woff2/PretendardVariable.woff2
  src/app/globals.css
  src/components/Pagination.tsx
Labels: ➕Add

#246 🔀 fix: 구매 내역 이미지 링크 수정
  src/app/my/components/HistoryCard.tsx
Labels: 🐛BugFix

#248 🔀 feat: 최종 배포테스트 - 오류 수정
  public/font/pretendardvariable.css
  public/font/woff2/PretendardVariable.woff2
  src/app/auth/login/LoginForm.tsx
  src/app/globals.css
  src/app/my/components/HistoryCard.tsx
  src/app/products/[id]/PostForm.tsx
  src/app/products/[id]/ProductPostForm.tsx
  src/app/products/components/SortToggle.tsx
  src/components/Carousel.tsx
  src/components/Pagination.tsx
  src/data/actions/bookmark.ts
  src/data/actions/carts.ts
  src/data/actions/product.ts
  src/data/functions/carts.ts
  src/data/functions/order.ts
Labels: 🐛BugFix, 💡Feature, 🎨Style

#249 🔀 fix: 상품 상세 페이지 찜하기 추가/삭제 시 캐시 무효화 코드 추가
  src/components/ProductImg.tsx
  src/data/actions/bookmark.ts
Labels: 🐛BugFix, 💡Feature

#250 🔀 fix: 회원가입 화면 모바일 padding 축소
  src/app/auth/signup/page.tsx
Labels: 🎨Style

#252 🔀 feat: 로고 이미지 교체
  public/icon/holataja_logo.svg
Labels: 💡Feature

#253 🔀 feat: 최종 배포테스트 merge
  public/icon/holataja_logo.svg
  src/app/auth/signup/page.tsx
  src/app/products/components/KeySoundDemo.tsx
  src/components/ProductImg.tsx
  src/data/actions/bookmark.ts
Labels: 🐛BugFix, 🎨Style

#256 🔀 fix: 시멘틱 구조 강화 (상품 목록 화면/장바구니 화면)
  src/app/carts/components/CartContainer.tsx
  src/app/carts/components/CartSummary.tsx
  src/app/products/components/SortToggle.tsx
  src/components/Carousel.tsx
Labels: 🎨Style

#257 🔀 fix: 시멘틱 구조 강화
  src/app/carts/components/CartContainer.tsx
  src/app/carts/components/CartSummary.tsx
  src/app/products/components/SortToggle.tsx
  src/components/Carousel.tsx
Labels: 🎨Style, 🔐Accessibility

#262 🔀 docs: 리드미 1차 초안 작성
  README.md
Labels: 📝Documentation

#266 🔀 Docs: README 2차 수정(로고, 오타, 프로젝트 구조도)
  README.md
Labels: 📝Documentation
