Repository FRONTENDBOOTCAMP-13th/Final-15-HOLATAJA, pull requests merged in 2025-07, with the labels that each got.

#19 🔀 feat: 공용 input 컴포넌트 제작
  src/app/globals.css
  src/components/Input.tsx
  src/pages/.gitkeep
Labels: 💡Feature, 🟠 Priority : High

#17 🔀 feat: 버튼 컴포넌트 구현
  src/app/globals.css
  src/components/Button.tsx
Labels: 💡Feature

#20 🔀 feat: 캐러셀 컴포넌트 구현 완료
  package-lock.json
  package.json
  public/carousel_images/carousel-image1.webp
  public/carousel_images/carousel-image10.webp
  public/carousel_images/carousel-image11.webp
  public/carousel_images/carousel-image12.webp
  public/carousel_images/carousel-image2.webp
  public/carousel_images/carousel-image3.webp
  public/carousel_images/carousel-image4.webp
  public/carousel_images/carousel-image5.webp
  public/carousel_images/carousel-image6.webp
  public/carousel_images/carousel-image7.webp
  public/carousel_images/carousel-image8.webp
  public/carousel_images/carousel-image9.webp
  src/components/Carousel.tsx
Labels: 💡Feature

#24 🔀 feat: 헤더 푸터 추가
  public/icon/logo.svg
  public/icon/off_star.svg
  public/icon/on_star.svg
  src/app/layout.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/Icons.tsx
Labels: 💡Feature

#26 🔀 feat: 체크 박스 버튼 컴포넌트 구현 완료
  src/components/CheckboxButton.tsx
Labels: 💡Feature, 🎨Style

#31 🔀 feat: 리뷰 카드 컴포넌트 구현
  src/components/ReviewCard.tsx
Labels: 💡Feature

#33 🔀 feat: 상품 카드 컴포넌트 구현 완료
  src/components/ProductCard.tsx
  src/components/ProductImg.tsx
Labels: 💡Feature

#43 🔀 test: API test 파일 공유(posts/replies)
  api/bruno/HolaTAJA API test/Q&A/01_목록 조회/게시물 목록 조회.bru
  api/bruno/HolaTAJA API test/Q&A/01_목록 조회/내가 작성한 게시물 목록 조회.bru
  api/bruno/HolaTAJA API test/Q&A/folder.bru
  api/bruno/HolaTAJA API test/Q&A/게시물 등록.bru
  api/bruno/HolaTAJA API test/Q&A/게시물 삭제.bru
  api/bruno/HolaTAJA API test/Q&A/게시물 상세 조회.bru
  api/bruno/HolaTAJA API test/Q&A/게시물 수정.bru
  api/bruno/HolaTAJA API test/댓글/folder.bru
  api/bruno/HolaTAJA API test/댓글/내 후기 목록 조회.bru
  api/bruno/HolaTAJA API test/댓글/상품 후기 목록 조회.bru
  api/bruno/HolaTAJA API test/댓글/후기 등록.bru
  api/bruno/HolaTAJA API test/댓글/후기 삭제.bru
  api/bruno/HolaTAJA API test/댓글/후기 수정.bru
Labels: 🧪Test, ➕Add

#42 🔀 test: API test 파일 공유(cart/order)
  api/bruno/HolaTAJA API test/bruno.json
  api/bruno/HolaTAJA API test/collection.bru
  api/bruno/HolaTAJA API test/environments/환경변수.bru
  api/bruno/HolaTAJA API test/구매/구매 내역 목록.bru
  api/bruno/HolaTAJA API test/구매/구매 내역 상세 확인.bru
  api/bruno/HolaTAJA API test/구매/상품 구매.bru
  api/bruno/HolaTAJA API test/사용자 관리/로그인.bru
  api/bruno/HolaTAJA API test/사용자 관리/회원 목록 조회.bru
  api/bruno/HolaTAJA API test/사용자 관리/회원가입.bru
  api/bruno/HolaTAJA API test/장바구니/장바구니 담기.bru
  api/bruno/HolaTAJA API test/장바구니/장바구니 삭제.bru
  api/bruno/HolaTAJA API test/장바구니/장바구니 수량 조절.bru
  api/bruno/HolaTAJA API test/장바구니/장바구니 조회.bru
Labels: 🧪Test, ➕Add

#41 🔀 test: API test 파일 공유(products/bookmark/seller)
  api/bruno/HolaTAJA API test/bruno.json
  api/bruno/HolaTAJA API test/collection.bru
  api/bruno/HolaTAJA API test/environments/HolaTAJA.bru
  api/bruno/HolaTAJA API test/북마크(찜)/folder.bru
  api/bruno/HolaTAJA API test/북마크(찜)/북마크 1건 조회.bru
  api/bruno/HolaTAJA API test/북마크(찜)/북마크 삭제.bru
  api/bruno/HolaTAJA API test/북마크(찜)/북마크(찜하기) 조회.bru
  api/bruno/HolaTAJA API test/북마크(찜)/북마크(찜하기) 추가.bru
  api/bruno/HolaTAJA API test/상품 정보/folder.bru
  api/bruno/HolaTAJA API test/상품 정보/상품 상세 조회.bru
  api/bruno/HolaTAJA API test/상품 정보/상품 정보 조회.bru
  api/bruno/HolaTAJA API test/판매자/folder.bru
  api/bruno/HolaTAJA API test/판매자/상품 삭제.bru
  api/bruno/HolaTAJA API test/판매자/판매 상품 등록.bru
  api/bruno/HolaTAJA API test/판매자/판매 상품 목록 조회.bru
  api/bruno/HolaTAJA API test/판매자/판매 상품 수정.bru
  api/bruno/HolaTAJA API test/판매자/판매 상품 이미지 등록.bru
  api/bruno/openmarket/01_회원/02_회원 정보 수정/folder.bru
  api/bruno/openmarket/01_회원/03_회원 목록 조회/folder.bru
  api/bruno/openmarket/01_회원/04_회원 정보 조회/folder.bru
  api/bruno/openmarket/02_일반 회원/02_구매/folder.bru
  api/bruno/openmarket/02_일반 회원/03_구매 후기/folder.bru
  api/bruno/openmarket/02_일반 회원/04_장바구니/folder.bru
  api/bruno/openmarket/02_일반 회원/05_북마크(찜하기)/folder.bru
  api/bruno/openmarket/02_일반 회원/06_알림메세지/folder.bru
  api/bruno/openmarket/02_일반 회원/folder.bru
  api/bruno/openmarket/03_판매 회원/folder.bru
  api/bruno/openmarket/04_관리자/02_코드 관리/folder.bru
  api/bruno/openmarket/04_관리자/02_코드 관리/코드 등록(tripTheme).bru
  api/bruno/openmarket/04_관리자/02_코드 관리/코드 삭제.bru
  api/bruno/openmarket/04_관리자/02_코드 관리/코드 수정.bru
  api/bruno/openmarket/04_관리자/03_통계 조회/folder.bru
  api/bruno/openmarket/04_관리자/04_설정 관리/folder.bru
  api/bruno/openmarket/04_관리자/folder.bru
  api/bruno/openmarket/05_게시판(QnA, 공지 등)/01_목록 조회/folder.bru
  api/bruno/openmarket/05_게시판(QnA, 공지 등)/02_댓글/folder.bru
  api/bruno/openmarket/05_게시판(QnA, 공지 등)/folder.bru
  api/bruno/openmarket/05_게시판(QnA, 공지 등)/private 게시물 상세 조회.bru
  api/bruno/openmarket/05_게시판(QnA, 공지 등)/게시물 등록(private).bru
  api/bruno/openmarket/05_게시판(QnA, 공지 등)/게시물 등록(상품 Q&A).bru
  api/bruno/openmarket/05_게시판(QnA, 공지 등)/게시물 등록(상품 Q&A, private).bru
  api/bruno/openmarket/05_게시판(QnA, 공지 등)/게시물 등록(태그 추가).bru
  api/bruno/openmarket/05_게시판(QnA, 공지 등)/게시물 삭제.bru
  api/bruno/openmarket/05_게시판(QnA, 공지 등)/게시물 상세 조회.bru
  api/bruno/openmarket/05_게시판(QnA, 공지 등)/게시물 수정(private 게시물 공유).bru
  api/bruno/openmarket/05_게시판(QnA, 공지 등)/게시물 수정.bru
  api/bruno/openmarket/06_시스템/folder.bru
Labels: 🧪Test, ➕Add

#45 🔀 test: Bruno API test 파일 정리
  api/bruno/HolaTAJA API test/1_ 사용자 관리/1-1_ 회원가입/folder.bru
  api/bruno/HolaTAJA API test/1_ 사용자 관리/1-2_ 로그인/folder.bru
  api/bruno/HolaTAJA API test/1_ 사용자 관리/1-3_ 회원정보/folder.bru
  api/bruno/HolaTAJA API test/1_ 사용자 관리/folder.bru
  api/bruno/HolaTAJA API test/Q&A/folder.bru
  api/bruno/HolaTAJA API test/게시판(Q&A)/folder.bru
  api/bruno/HolaTAJA API test/게시판(Q&A)/게시물 등록.bru
  api/bruno/HolaTAJA API test/게시판(Q&A)/게시물 목록 조회.bru
  api/bruno/HolaTAJA API test/게시판(Q&A)/게시물 삭제.bru
  api/bruno/HolaTAJA API test/게시판(Q&A)/게시물 상세 조회.bru
  api/bruno/HolaTAJA API test/게시판(Q&A)/게시물 수정.bru
  api/bruno/HolaTAJA API test/게시판(Q&A)/내가 작성한 게시물 목록 조회.bru
  api/bruno/HolaTAJA API test/댓글(구매 후기)/folder.bru
  api/bruno/HolaTAJA API test/댓글(구매 후기)/내 후기 목록 조회.bru
  api/bruno/HolaTAJA API test/댓글(구매 후기)/상품 후기 목록 조회.bru
  api/bruno/HolaTAJA API test/댓글(구매 후기)/후기 등록.bru
  api/bruno/HolaTAJA API test/댓글(구매 후기)/후기 삭제.bru
  api/bruno/HolaTAJA API test/댓글(구매 후기)/후기 수정.bru
  api/bruno/HolaTAJA API test/댓글/folder.bru
  api/bruno/HolaTAJA API test/북마크(찜)/folder.bru
  api/bruno/HolaTAJA API test/북마크(찜)/북마크 리스트.bru
  api/bruno/HolaTAJA API test/사용자 관리/folder.bru
  api/bruno/HolaTAJA API test/사용자 관리/로그인.bru
  api/bruno/HolaTAJA API test/사용자 관리/이메일 로그인.bru
  api/bruno/HolaTAJA API test/사용자 관리/이메일 중복체크.bru
  api/bruno/HolaTAJA API test/사용자 관리/이메일 회원가입.bru
  api/bruno/HolaTAJA API test/사용자 관리/회원 목록 조회.bru
  api/bruno/HolaTAJA API test/사용자 관리/회원 정보 수정.bru
  api/bruno/HolaTAJA API test/사용자 관리/회원 정보 조회.bru
  api/bruno/HolaTAJA API test/사용자 관리/회원가입.bru
  api/bruno/HolaTAJA API test/상품 정보/folder.bru
  api/bruno/HolaTAJA API test/장바구니/folder.bru
  api/bruno/HolaTAJA API test/판매자/folder.bru
  api/bruno/HolaTAJA API test/판매자/판매 상품 삭제.bru
Labels: 🗑️Remove, 🧪Test

#50 🔀 fix: tab 공통 컴포넌트 props 받아서 넘길 수 있도록 수정
  src/components/Tab.tsx
Labels: 🐛BugFix, ♻️Refactor, 💡Feature

#52 🔀 style: 레이아웃 스타일 변경
  src/app/layout.tsx
Labels: 🎨Style, 🚑️Hotfix

#62 🔀 feat: 상품목록 UI 구현 및 조회 API 연결 완료
  public/icon/search.svg
  public/product_images/holataja_circle.webp
  src/app/products/CategoryToggle.tsx
  src/app/products/SearchBar.tsx
  src/app/products/page.tsx
  src/components/Carousel.tsx
  src/components/ProductCard.tsx
Labels: 💡Feature, ➕Add

#66 🔀 feat: 회원가입-로그인 페이지 구현
  src/app/auth/login/page.tsx
  src/app/auth/signup/page.tsx
  src/components/Input.tsx
  src/hooks/useAxiosInstance.tsx
Labels: 💡Feature, 🟠 Priority : High

#72 🔀 fix: 상품 목록 페이지 - 이미지 파일 경로 연결 부분 수정
  public/product_images/nuphy_air75/nuphy_air75_basaltblack_detail_01.webp
  public/product_images/nuphy_air75/nuphy_air75_basaltblack_detail_02.webp
  public/product_images/nuphy_air75/nuphy_air75_basaltblack_detail_blue.webp
  public/product_images/nuphy_air75/nuphy_air75_basaltblack_detail_brown.webp
  public/product_images/nuphy_air75/nuphy_air75_basaltblack_detail_red.webp
  public/product_images/nuphy_air75/nuphy_air75_detail_01.webp
  public/product_images/nuphy_air75/nuphy_air75_info_01.webp
  public/product_images/nuphy_air75/nuphy_air75_info_02.webp
  public/product_images/nuphy_air75/nuphy_air75_info_03.webp
  public/product_images/nuphy_air75/nuphy_air75_info_04.webp
  public/product_images/nuphy_air75/nuphy_air75_info_05.webp
  public/product_images/nuphy_air75/nuphy_air75_ionicwhite_detail_01.webp
  public/product_images/nuphy_air75/nuphy_air75_ionicwhite_detail_02.webp
  public/product_images/nuphy_air75/nuphy_air75_ionicwhite_detail_blue.webp
  public/product_images/nuphy_air75/nuphy_air75_ionicwhite_detail_brown.webp
  public/product_images/nuphy_air75/nuphy_air75_ionicwhite_detail_red.webp
  public/product_images/nuphy_air75/nuphy_air75_lunagray_detail_01.webp
  public/product_images/nuphy_air75/nuphy_air75_lunagray_detail_02.webp
  public/product_images/nuphy_air75/nuphy_air75_lunagray_detail_blue.webp
  public/product_images/nuphy_air75/nuphy_air75_lunagray_detail_brown.webp
  public/product_images/nuphy_air75/nuphy_air75_lunagray_detail_red.webp
  public/product_images/nuphy_bh65/nuphy_bh65_darkmatter_JadeGaming_detail_01.webp
  public/product_images/nuphy_bh65/nuphy_bh65_darkmatter_JadeGaming_info_01.webp
  public/product_images/nuphy_bh65/nuphy_bh65_darkmatter_JadePro_detail_01.webp
  public/product_images/nuphy_bh65/nuphy_bh65_darkmatter_JadePro_info_01.webp
  public/product_images/nuphy_bh65/nuphy_bh65_darkmatter_detail_01.webp
  public/product_images/nuphy_bh65/nuphy_bh65_darkmatter_detail_02.webp
  public/product_images/nuphy_bh65/nuphy_bh65_darkmatter_detail_03.webp
  public/product_images/nuphy_bh65/nuphy_bh65_darkmatter_detail_04.webp
  public/product_images/nuphy_bh65/nuphy_bh65_darkmatter_detail_05.webp
  public/product_images/nuphy_bh65/nuphy_bh65_darkmatter_detail_06.webp
  public/product_images/nuphy_bh65/nuphy_bh65_darkmatter_info_01.webp
  public/product_images/nuphy_bh65/nuphy_bh65_darkmatter_info_02.webp
  public/product_images/nuphy_bh65/nuphy_bh65_darkmatter_info_03.webp
  public/product_images/nuphy_bh65/nuphy_bh65_darkmatter_info_04.webp
  public/product_images/nuphy_field75/nuphy_field75_spacegray_detail_01.webp
  public/product_images/nuphy_field75/nuphy_field75_spacegray_detail_02.webp
  public/product_images/nuphy_field75/nuphy_field75_spacegray_detail_03.webp
  public/product_images/nuphy_field75/nuphy_field75_spacegray_detail_04.webp
  public/product_images/nuphy_field75/nuphy_field75_spacegray_detail_05.webp
  public/product_images/nuphy_field75/nuphy_field75_spacegray_detail_06.webp
  public/product_images/nuphy_field75/nuphy_field75_spacegray_info_01.webp
  public/product_images/nuphy_field75/nuphy_field75_spacegray_info_02.webp
  public/product_images/nuphy_field75/nuphy_field75_spacegray_info_03.webp
  public/product_images/nuphy_field75/nuphy_field75_spacegray_info_04.webp
  public/product_images/nuphy_field75/nuphy_field75_spacegray_jade_detail_01.webp
  public/product_images/nuphy_field75/nuphy_field75_spacegray_jade_info_01.webp
  public/product_images/nuphy_field75/nuphy_field75_spacegray_white_detail_01.webp
  public/product_images/nuphy_field75/nuphy_field75_spacegray_white_info_01.webp
  src/app/products/page.tsx
  src/components/ProductImg.tsx
Labels: 💡Feature, 🎨Style, ➕Add

#75 🔀 style: lightgray 색상값 수정, 반응형 텍스트 크기 설정(rem 변경)
  src/app/globals.css
  src/app/layout.tsx
Labels: 🎨Style

#76 🔀 feature: 상품 상세 페이지 UI 구현
  src/app/products/[id]/page.tsx
  src/components/QnA.tsx
Labels: 💡Feature

#81 🔀 style: Title, Header 컴포넌트 반응형 구현, Header 아이콘 버튼 추가
  src/app/globals.css
  src/app/layout.tsx
  src/components/Header.tsx
Labels: 💡Feature, 🎨Style

#83 🔀 refactor: 마이페이지 href 수정
  src/components/Header.tsx
Labels: ♻️Refactor

#64 🔀 feat: 결제 페이지 구현
  src/app/checkout/page.tsx
  src/components/Footer.tsx
Labels: 💡Feature

#85 🔀 refactor: footer 컴포넌트 디자인 수정
  src/components/Footer.tsx
Labels: 🎨Style

#90 🔀 feat: 컴포넌트 프리뷰 페이지 구현
  src/app/components-preview/page.tsx
  src/components/ProductCard.tsx
Labels: 💡Feature, 🎨Style

#96 🔀 refactor: 회원가입 페이지 next.js 표준으로 리팩토링
  package-lock.json
  package.json
  src/app/auth/signup/SignupForm.tsx
  src/app/auth/signup/action.ts
  src/app/auth/signup/page.tsx
  src/types/userType.ts
Labels: ♻️Refactor

#97 🔀 feat: next config 설정 추가, 상품 상세 조회 기능 구현, 타입 파일 생성
  next.config.ts
  src/app/products/[id]/page.tsx
  src/components/ProductImg.tsx
  src/data/functions/product.ts
  src/types/api.ts
  src/types/product.ts
Labels: ♻️Refactor, 💡Feature

#99 🔀 refactor: 로그인 페이지 리펙토링
  src/app/auth/login/LoginForm.tsx
  src/app/auth/login/action.ts
  src/app/auth/login/page.tsx
  src/app/auth/signup/SignupForm.tsx
  src/app/auth/signup/action.ts
  src/app/auth/signup/page.tsx
  src/store/authStore.ts
  src/types/.gitkeep
  src/types/apiType.ts
  src/types/userType.ts
Labels: ♻️Refactor

#110 🔀refactor: 상품 목록 페이지 API 호출 방식 변경 적용
  src/app/products/page.tsx
  src/components/ProductCard.tsx
  src/data/functions/product.ts
  src/types/product.ts
Labels: ♻️Refactor

#116 🔀 feat: 상품 목록 페이지-상세 보기 페이지 연결 완료
  src/components/ProductCard.tsx
  src/components/ProductImg.tsx
Labels: 💡Feature, 🎨Style

#118 🔀 feat: 구매 후기 조회 기능 리팩토링, 페이지에 따른 목록 조회 구현, 구매 후기 컴포넌트 스타일 변경
  src/app/products/[id]/Review.tsx
  src/app/products/[id]/page.tsx
  src/components/ReviewCard.tsx
Labels: ♻️Refactor, 💡Feature, 🎨Style

#119 🔀feat: 마이페이지-찜 목록 탭 UI 구현 완료
  src/app/my/components/BookmarkCard.tsx
  src/app/my/components/BookmarkTab.tsx
  src/app/my/components/OrderTab.tsx
  src/app/my/page.tsx
Labels: 💡Feature, 🎨Style

#124 🔀 feat: 구매 후기 수정/삭제 UI, 구매 후기 삭제 기능 구현, 모달 컴포넌트 리팩토링
  src/app/products/[id]/Review.tsx
  src/app/products/[id]/page.tsx
  src/components/Button.tsx
  src/components/Modal.tsx
  src/components/ReviewCard.tsx
  src/data/actions/review.ts
  src/data/functions/review.ts
Labels: ♻️Refactor, 💡Feature, 🎨Style

#126 🔀 feat: error/not-found 페이지 생성 완료
  src/app/error.tsx
  src/app/not-found.tsx
Labels: 💡Feature

#128 🔀 feat: 마이페이지: 회원정보 수정 완료
  src/app/auth/login/LoginForm.tsx
  src/app/my/components/UserInfo.tsx
  src/app/my/page.tsx
  src/data/actions/auth.ts
  src/store/authStore.ts
  src/types/api.ts
  src/types/apiType.ts
  src/types/user.ts
Labels: 💡Feature

#131 🔀 feat: 장바구니 조회 및 삭제 기능 구현 완료
  api/bruno/HolaTAJA API test/사용자 관리/이메일 로그인.bru
  api/bruno/HolaTAJA API test/사용자 관리/회원 정보 조회.bru
  api/bruno/HolaTAJA API test/상품 정보/상품 상세 조회.bru
  api/bruno/HolaTAJA API test/상품 정보/상품 정보 조회.bru
  api/bruno/HolaTAJA API test/장바구니/장바구니 담기.bru
  src/app/cart/components/CartContainer.tsx
  src/app/cart/components/CartItem.tsx
  src/app/cart/components/CartSummary.tsx
  src/app/cart/page.tsx
  src/app/carts/components/CartContainer.tsx
  src/app/carts/components/CartProductCard.tsx
  src/app/carts/components/CartSummary.tsx
  src/app/carts/page.tsx
  src/components/QuantityCount.tsx
  src/data/functions/carts.ts
  src/types/cart.ts
Labels: ♻️Refactor, 💡Feature, 🎨Style

#142 🔀 feat: Pagination 컴포넌트 구현 완료, 마이페이지 구매내역 탭 및 컴포넌트 프리뷰 페이지 반영 완료
  src/app/components-preview/page.tsx
  src/app/my/components/OrderTab.tsx
  src/app/my/components/QnATab.tsx
  src/app/my/page.tsx
  src/components/Pagination.tsx
  src/data/functions/order.ts
Labels: 💡Feature

#148 🔀 feat: 장바구니 페이지 데이터 조회, 삭제 기능 구현
  src/app/carts/components/CartContainer.tsx
  src/app/carts/components/CartProductCard.tsx
  src/app/carts/components/CartSummary.tsx
  src/app/carts/page.tsx
  src/components/PrdInfoQuantity.tsx
  src/components/QuantityCount.tsx
  src/data/functions/carts.ts
  src/hooks/useDebounce.tsx
  src/types/api.ts
  src/types/cart.ts
Labels: ♻️Refactor, 💡Feature, 🎨Style

#152 🔀 feat: 상품 찜하기 조회/추가/삭제 기능 구현 완료
  src/app/my/[id]/page.tsx
  src/app/my/components/BookmarkCard.tsx
  src/app/my/components/BookmarkTab.tsx
  src/app/my/components/OrderTab.tsx
  src/app/my/page.tsx
  src/app/products/[id]/page.tsx
  src/app/products/components/CategoryToggle.tsx
  src/app/products/components/SearchBar.tsx
  src/app/products/page.tsx
  src/components/ProductCard.tsx
  src/components/ProductImg.tsx
  src/data/actions/bookmark.ts
  src/data/functions/bookmark.ts
  src/data/functions/product.ts
  src/types/bookmark.ts
  src/types/product.ts
Labels: 🐛BugFix, 💡Feature, ➕Add

#153 🔀 feat: 상품 찜하기 추가/삭제 기능 구현 완료 (추가 병합)
  src/app/products/[id]/page.tsx
  src/components/ProductCard.tsx
  src/components/ProductImg.tsx
Labels: 💡Feature

#154 🔀 feat: 상품 상세 페이지 장바구니에 추가 기능 구현
  src/app/products/[id]/ProductPostForm.tsx
  src/app/products/[id]/page.tsx
  src/components/Modal.tsx
  src/components/PrdInfoQuantity.tsx
  src/data/actions/product.ts
Labels: ♻️Refactor, 💡Feature, 🎨Style

#156 🔀 conf: DB init 파일 및 이미지 파일 업데이트
  api/dbinit/team/data.js
  api/dbinit/team/uploadFiles/holataja_circle.webp
  api/dbinit/team/uploadFiles/keyboardSound_sample.m4a
  api/dbinit/team/uploadFiles/nuphy_air75_basaltblack_detail_01.webp
  api/dbinit/team/uploadFiles/nuphy_air75_basaltblack_detail_02.webp
  api/dbinit/team/uploadFiles/nuphy_air75_basaltblack_detail_blue.webp
  api/dbinit/team/uploadFiles/nuphy_air75_basaltblack_detail_brown.webp
  api/dbinit/team/uploadFiles/nuphy_air75_basaltblack_detail_red.webp
  api/dbinit/team/uploadFiles/nuphy_air75_detail_01.webp
  api/dbinit/team/uploadFiles/nuphy_air75_info_01.webp
  api/dbinit/team/uploadFiles/nuphy_air75_info_02.webp
  api/dbinit/team/uploadFiles/nuphy_air75_info_03.webp
  api/dbinit/team/uploadFiles/nuphy_air75_info_04.webp
  api/dbinit/team/uploadFiles/nuphy_air75_info_05.webp
  api/dbinit/team/uploadFiles/nuphy_air75_ionicwhite_detail_01.webp
  api/dbinit/team/uploadFiles/nuphy_air75_ionicwhite_detail_02.webp
  api/dbinit/team/uploadFiles/nuphy_air75_ionicwhite_detail_blue.webp
  api/dbinit/team/uploadFiles/nuphy_air75_ionicwhite_detail_brown.webp
  api/dbinit/team/uploadFiles/nuphy_air75_ionicwhite_detail_red.webp
  api/dbinit/team/uploadFiles/nuphy_air75_lunagray_detail_01.webp
  api/dbinit/team/uploadFiles/nuphy_air75_lunagray_detail_02.webp
  api/dbinit/team/uploadFiles/nuphy_air75_lunagray_detail_blue.webp
  api/dbinit/team/uploadFiles/nuphy_air75_lunagray_detail_brown.webp
  api/dbinit/team/uploadFiles/nuphy_air75_lunagray_detail_red.webp
  api/dbinit/team/uploadFiles/nuphy_bh65_darkmatter_JadeGaming_detail_01.webp
  api/dbinit/team/uploadFiles/nuphy_bh65_darkmatter_JadeGaming_info_01.webp
  api/dbinit/team/uploadFiles/nuphy_bh65_darkmatter_JadePro_detail_01.webp
  api/dbinit/team/uploadFiles/nuphy_bh65_darkmatter_JadePro_info_01.webp
  api/dbinit/team/uploadFiles/nuphy_bh65_darkmatter_detail_01.webp
  api/dbinit/team/uploadFiles/nuphy_bh65_darkmatter_detail_02.webp
  api/dbinit/team/uploadFiles/nuphy_bh65_darkmatter_detail_03.webp
  api/dbinit/team/uploadFiles/nuphy_bh65_darkmatter_detail_04.webp
  api/dbinit/team/uploadFiles/nuphy_bh65_darkmatter_detail_05.webp
  api/dbinit/team/uploadFiles/nuphy_bh65_darkmatter_detail_06.webp
  api/dbinit/team/uploadFiles/nuphy_bh65_darkmatter_info_01.webp
  api/dbinit/team/uploadFiles/nuphy_bh65_darkmatter_info_02.webp
  api/dbinit/team/uploadFiles/nuphy_bh65_darkmatter_info_03.webp
  api/dbinit/team/uploadFiles/nuphy_bh65_darkmatter_info_04.webp
  api/dbinit/team/uploadFiles/nuphy_field75_spacegray_detail_01.webp
  api/dbinit/team/uploadFiles/nuphy_field75_spacegray_detail_02.webp
  api/dbinit/team/uploadFiles/nuphy_field75_spacegray_detail_03.webp
  api/dbinit/team/uploadFiles/nuphy_field75_spacegray_detail_04.webp
  api/dbinit/team/uploadFiles/nuphy_field75_spacegray_detail_05.webp
  api/dbinit/team/uploadFiles/nuphy_field75_spacegray_detail_06.webp
  api/dbinit/team/uploadFiles/nuphy_field75_spacegray_info_01.webp
  api/dbinit/team/uploadFiles/nuphy_field75_spacegray_info_02.webp
  api/dbinit/team/uploadFiles/nuphy_field75_spacegray_info_03.webp
  api/dbinit/team/uploadFiles/nuphy_field75_spacegray_info_04.webp
  api/dbinit/team/uploadFiles/nuphy_field75_spacegray_jade_detail_01.webp
  api/dbinit/team/uploadFiles/nuphy_field75_spacegray_jade_info_01.webp
  api/dbinit/team/uploadFiles/nuphy_field75_spacegray_white_detail_01.webp
  api/dbinit/team/uploadFiles/nuphy_field75_spacegray_white_info_01.webp
  api/dbinit/team/uploadFiles/sample-bugatti.png
  api/dbinit/team/uploadFiles/user-muzi.png
  api/dbinit/team/uploadFiles/user-neo.png
Labels: 🎉Init

#160 🔀 fix: header 로고 파일 변경 적용 / footer 모바일 UI 수정
  public/icon/holataja_logo.svg
  public/icon/logo.svg
  src/components/Footer.tsx
  src/components/Header.tsx
Labels: 🐛BugFix, 🎨Style, 🗑️Remove, ➕Add

#161 🔀 style: 찜 목록/구매 내역 탭 UI 수정
  api/bruno/HolaTAJA API test/구매/상품 구매.bru
  api/bruno/HolaTAJA API test/댓글(구매 후기)/Q&A 답변 등록.bru
  api/bruno/HolaTAJA API test/북마크(찜)/북마크 리스트 조회.bru
  api/bruno/HolaTAJA API test/북마크(찜)/북마크 추가.bru
  api/bruno/HolaTAJA API test/북마크(찜)/사용자 북마크 리스트 조회.bru
  api/bruno/HolaTAJA API test/사용자 관리/이메일 로그인(사용자).bru
  api/bruno/HolaTAJA API test/사용자 관리/이메일 로그인(판매자).bru
  api/bruno/HolaTAJA API test/상품 정보/상품 목록 조회.bru
  api/bruno/HolaTAJA API test/상품 정보/상품 상세 조회.bru
  api/bruno/HolaTAJA API test/상품 정보/이미지 호출.bru
  api/bruno/HolaTAJA API test/장바구니/장바구니 추가.bru
  src/app/my/components/BookmarkCard.tsx
  src/app/my/components/BookmarkTab.tsx
  src/app/my/components/OrderTab.tsx
Labels: 🎨Style, ➕Add

#164 🔀 fix: 마이페이지 새로 고침 시 로그인 요청 뜨는 버그와 회원정보 수정 후 데이터 바로 안 뜨는 문제 해결
  src/app/my/components/UserInfo.tsx
  src/store/authStore.ts
Labels: 🐛BugFix, 🎨Style

#167 🔀 feat: 찜하기 버튼 클릭 시 로그인 여부 확인하는 기능 추가 완료
  src/components/Modal.tsx
  src/components/ProductImg.tsx
Labels: 💡Feature, 🎨Style
